// <auto-generated />
namespace HRIS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class removeuserlinktotable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removeuserlinktotable));
        
        string IMigrationMetadata.Id
        {
            get { return "201711240606479_remove-user-link-to-table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
